# Generated by Django 3.1.4 on 2021-03-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitconvertor', '0002_auto_20210325_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
