# Generated by Django 3.1.4 on 2021-03-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencyconvertor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed']},
        ),
    ]
